### ISSUE TITLE
`Object.keys` triggers `disallowEmberKeys`

### ISSUE THREAD

**Issue by rwjblue** [minichate/jscs-ember-deprecations#5]
![screenshot](https://monosnap.com/file/R13F9EKrLQzRFQ2DMccgyLomMsZMhv.png)

**Comment by minichate** [comment]
Should be fixed in `0.0.17`

IIRC the fix was in https://github.com/minichate/jscs-ember-deprecations/commit/c2221c8760da4777a3d9c45282a8eccbcd26d8de

**Comment by rwjblue** [comment]
D'oh! I should've tested master first, sorry about that!

**Comment by minichate** [comment]
@rwjblue nah, it was a silly bug :) Ironically, I found it by testing against the `ember-json-schema` codebase!
